### ISSUE TITLE
feat : Make the Reload button more attractive.

### ISSUE THREAD

**Issue by codingninja11** [codingninja11/TypeTwister#2]
Make sure that the button is visually interactive.

![image](https://user-images.githubusercontent.com/64359203/135498262-49e4c61d-0565-4d89-bac8-1d68f1460d93.png)

**Comment by jma26** [comment]
Hey! I'm interested in taking this feature enhancement on. Do you have any reference or design requirements for the reload button?

**Comment by codingninja11** [comment]
> Hey! I'm interested in taking this feature enhancement on. Do you have any reference or design requirements for the reload button?

Ok go for it.You can add anything you like make sure it doesn't affects the contrast of the page.

**Comment by BajraYeJoon** [comment]
is this available>
??
